title: "Hololive TCG Wiki"
description: "A comprehensive guide to the Hololive Official Card Game."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://somostve.github.io/hololive-tcg-guide" # your GitHub Pages URL
remote_theme: "mmistakes/minimal-mistakes" # Use the remote theme instead of the local theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      permalink: "/:title/"
